[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# (string value)
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `python-dateutil` to requirements.txt
# timezone =

# max length of characters to apply to the
# "rev" field of migrations, which is also used to
# generate filenames. Note that this length includes
# the 4 characters that Alembic uses to separate
# rev ids from one another ("_" and ".").
# max_len = 20

# The character to use for generating revision ids
# Defaults to the lower-case hexadecimal characters.
# rev_id = [0-9a-f]

# The version path separator, applied between
# the directory and the version.
# version_path_separator = |

# The output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql://signalforge:signalforge_pass@localhost:5432/signalforge

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s